# Generated by Django 2.1.5 on 2019-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_file',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
